export const CREATE_MOVIE = "CREATE_MOVIE";
export const CREATE_MOVIE_ERROR = "CREATE_MOVIE_ERROR";
export const CREATE_MOVIE_RESET = "CREATE_MOVIE_RESET";
export const ADMIN_GET_MOVIE_DETAIL = "ADMIN_GET_MOVIE_DETAIL";
export const ADMIN_GET_MOVIE_DETAIL_ERR = "ADMIN_GET_MOVIE_DETAIL_ERR";
export const ADMIN_CLEAR_MOVIE_DETAIL = "ADMIN_CLEAR_MOVIE_DETAIL";
