export const GET_LIST_TICKET = "GET_LIST_TICKET";
export const BOOKING_TICKET = "BOOKING_TICKET";
export const BOOKING_SEATS = "BOOKING_SEATS";
export const RESET_BOOKING_SEATS = "RESET_BOOKING_SEATS";
export const REALTIME_BOOKING_SEATS = "REALTIME_BOOKING_SEATS";
